; epay-miuix PHP configuration
upload_max_filesize = 10M
post_max_size = 12M
max_execution_time = 60
memory_limit = 128M
date.timezone = Asia/Shanghai
display_errors = Off
log_errors = On
error_log = /dev/stderr
session.auto_start = Off
session.gc_maxlifetime = 3600
opcache.enable = 1
opcache.memory_consumption = 64
opcache.max_accelerated_files = 2000
